// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBhylNS6ZwVyglIfIYrub9rXwrJsABfwNs',
    appId: '1:739402620987:web:ee3c58ee930745604abc1e',
    messagingSenderId: '739402620987',
    projectId: 'foodapp-ab8f9',
    authDomain: 'foodapp-ab8f9.firebaseapp.com',
    storageBucket: 'foodapp-ab8f9.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDP_PG6tbjD9HTrGUqjh2bfENYA2dhhybk',
    appId: '1:739402620987:android:695274751a9b82d84abc1e',
    messagingSenderId: '739402620987',
    projectId: 'foodapp-ab8f9',
    storageBucket: 'foodapp-ab8f9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBpuR3BC26PNorT2tjUzBHqGTiW0WrJ9S0',
    appId: '1:739402620987:ios:9cee429bdc3cc47b4abc1e',
    messagingSenderId: '739402620987',
    projectId: 'foodapp-ab8f9',
    storageBucket: 'foodapp-ab8f9.firebasestorage.app',
    iosBundleId: 'com.example.foodApp',
  );
}
